### ISSUE TITLE
OmegaFold weights for Mac / apple silicon

### ISSUE THREAD

**Issue by linkerst** [HeliXonProtein/OmegaFold#75]
First of all, thank you very much for developing this great and incredible fast structure predictor! It is super useful for high throughput structure predictions.

Related to the issue raised here: https://github.com/HeliXonProtein/OmegaFold/issues/15#issuecomment-1214384825

Are the any plans to provide weights compatible with Mac silicon environment? I am able to run omegafold on my Mac but the result looks like a random set of atom coordinates. On a linux system everything works fine.

**Comment by fnachon** [comment]
It is fixed with the latest versions of pytorch for arm64 (2.5.1 ; 2.6.0)

**Comment by jsgro** [comment]
Not sure it's fixed.
Trying this on M1ProMax with just the sequence of Glucagon (sequence from PDB [1GCN](https://www.rcsb.org/structure/1GCN)) which is a simple alpha helix.
```
>glucagon1GNC
HSQGTFTSDYSKYLDSRRAQDFVQWLMNT
```
PyTorch 2.10.0 is the latest today (May 17, 2026) but I see only random structure.
Reverting to the suggested version of 2.6 does not fix it.

Using a code I found in another issue to check:

```
 python3 -c "import torch; print(torch.__version__); print('MPS available: '+str(torch.backends.mps.is_available())); print('MPS built in PyTorch: '+str(torch.backends.mps.is_built()))"
2.6.0
MPS available: True
MPS built in PyTorch: True
```

P.S. I followed the procedure installation for M1 from [issues/77](https://github.com/HeliXonProtein/OmegaFold/issues/77)

P.P.S. The sequence is correctly folded under Linux cluster.
